#!/usr/bin/env php
<?php

/*
 * OIDplus 2.0
 * Copyright 2019 - 2023 Daniel Marschall, ViaThinkSoft
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This script will be called before publishing a new version

namespace ViaThinkSoft\OIDplus\Plugins\AdminPages\SystemFileCheck;

for ($sysdir_depth=5; $sysdir_depth<=8; $sysdir_depth++) {
	// The plugin directory can be in plugins (i=5), userdata_pub/plugins (i=6), or userdata_pub/tenant/.../plugins/ (i=8)
	$candidate = __DIR__. str_repeat('/..', $sysdir_depth) . '/includes/oidplus.inc.php';
	if (file_exists($candidate)) {
		require_once $candidate;
		break;
	}
}

$argc = $_SERVER['argc']; // to please Eclipse for PHP
$argv = $_SERVER['argv']; // to please Eclipse for PHP

if (PHP_SAPI != 'cli') {
	die("This file can only be invoked in CLI mode.\n");
}

if ($argc != 1) {
	echo "Usage: ".$argv[0]."\n";
	exit(2);
}

$outdir = realpath(__DIR__.str_repeat('/..', $sysdir_depth).'/');
$exclude = [
	// Please keep in-sync with OIDplusPageAdminSystemFileCheck.class.php
	// TODO: !!! Exclude "unversioned" GIT/SVN files to avoid that development files slip get leaked
	realpath($checksum_file = __DIR__.'/../checksums.json'),
	realpath($outdir.'/userdata'),
	realpath($outdir.'/userdata_pub')
];

$ary = OIDplusPageAdminSystemFileCheck::getDirContents($outdir, $outdir, $exclude);

file_put_contents($checksum_file, json_encode($ary,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));
