#!/usr/bin/env php
<?php

/*
 * OIDplus 2.0
 * Copyright 2019 - 2021 Daniel Marschall, ViaThinkSoft
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$dir = __DIR__ . '/../';

// ---

$it = new RecursiveDirectoryIterator($dir);
foreach(new RecursiveIteratorIterator($it) as $file) {
	if (strpos(str_replace('\\','/',realpath($file)),'/vendor/') !== false) continue; // ignore third-party-code
	if (strpos(str_replace('\\','/',realpath($file)),'/bcrypt_worker.js') !== false) continue; // ignore third-party-code
	if (strpos(str_replace('\\','/',realpath($file)),'/userdata/') !== false) continue;
	if (strpos(str_replace('\\','/',realpath($file)),'/includes/classes/http_class.class.php') !== false) continue;
	if (strpos(str_replace('\\','/',realpath($file)),'/plugins/objectTypes/oid/WeidOidConverter.class.php') !== false) continue;
	if (($file->getExtension() == 'php') || ($file->getExtension() == 'js')) {
		$cont = file_get_contents($file);
		if (strpos($cont,'Daniel Marschall, ViaThinkSoft') === false) {
			$file = realpath($file);
			echo "Copyright missing: $file\n";
		}
	}
}

echo "Done.\n";
