#!/bin/bash

# Export tables "demo_*" into file setup/sql/example_access.sql
# We don't print to console because of encoding issues
mysqldump --default-character-set=utf8 --no-create-info --extended-insert=FALSE oidplus demo_iri demo_asn1id demo_ra demo_objects -r ../setup/sql/example_access.sql

# Remove database prefix
sed -i 's/`demo_/`/g' ../setup/sql/example_access.sql

# Avoid that there is a conflict with well known IDs (e.g. 2.999)
#sed -i 's/INSERT INTO `iri`/INSERT IGNORE INTO `iri`/g' ../setup/sql/example_access.sql
#sed -i 's/INSERT INTO `asn1id`/INSERT IGNORE INTO `asn1id`/g' ../setup/sql/example_access.sql

# Change `backticks` to [brackets]
sed -iE 's/`\([^`]\+\)`/\[\1\]/g' ../setup/sql/example_access.sql

# Change "\n" to "' + CHR(13) + '"
sed -i "s/\\\n/' \+ CHR(13) \+ '/g" ../setup/sql/example_access.sql

# Change \" to "
sed -i 's/\\"/"/g' ../setup/sql/example_access.sql

# Prepend "SET DATEFORMAT ymd;"
cat ../setup/sql/example_access.sql >> tmp
cat tmp > ../setup/sql/example_access.sql
rm tmp
