#!/bin/bash

# Export tables "demo_*" into file setup/sql/example_pgsql.sql
# We don't print to console because of encoding issues
mysqldump --default-character-set=utf8 --no-create-info --extended-insert=FALSE oidplus demo_iri demo_asn1id demo_ra demo_objects -r ../setup/sql/example_pgsql.sql

# Remove database prefix
sed -i 's/`demo_/`/g' ../setup/sql/example_pgsql.sql

# Avoid that there is a conflict with well known IDs (e.g. 2.999)
#sed -i 's/INSERT INTO `iri`/INSERT IGNORE INTO `iri`/g' ../setup/sql/example_pgsql.sql
#sed -i 's/INSERT INTO `asn1id`/INSERT IGNORE INTO `asn1id`/g' ../setup/sql/example_pgsql.sql

# Change '1' and '0' to true and false
sed -i 's/'1'/true/g' ../setup/sql/example_pgsql.sql
sed -i 's/'0'/false/g' ../setup/sql/example_pgsql.sql

# Change backticks to double quotes
sed -i 's/`/"/g' ../setup/sql/example_pgsql.sql

# Change \" to "
sed -i 's/\\"/"/g' ../setup/sql/example_pgsql.sql

# Change "\n" to "' || chr(10) || '"
sed -i "s/\\\n/' \|\| chr\(10\) \|\| '/g" ../setup/sql/example_pgsql.sql
