#!/bin/bash

# OIDplus 2.0
# Copyright 2019 - 2021 Daniel Marschall, ViaThinkSoft
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Export tables "demo_*" into file setup/sql/example_sqlite.sql
# We don't print to console because of encoding issues
mysqldump --default-character-set=utf8 --no-create-info --extended-insert=FALSE oidplus demo_iri demo_asn1id demo_ra demo_objects -r ../setup/sql/example_mysql.sql

# Remove database prefix
sed -i 's/`demo_/`/g' ../setup/sql/example_mysql.sql

# Avoid that there is a conflict with well known IDs (e.g. 2.999)
sed -i 's/INSERT INTO `iri`/INSERT IGNORE INTO `iri`/g' ../setup/sql/example_mysql.sql
sed -i 's/INSERT INTO `asn1id`/INSERT IGNORE INTO `asn1id`/g' ../setup/sql/example_mysql.sql

# Change \" to "
sed -i 's/\\"/"/g' ../setup/sql/example_pgsql.sql

# Change "\n" to "' || chr(10) || '"
sed -i "s/\\\n/' \|\| chr\(10\) \|\| '/g" ../setup/sql/example_pgsql.sql
