#!/bin/bash

# OIDplus 2.0
# Copyright 2019 - 2021 Daniel Marschall, ViaThinkSoft
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Export tables "demo_*" into file setup/sql/example_mssql.sql
# We don't print to console because of encoding issues
mysqldump --default-character-set=utf8 --no-create-info --extended-insert=FALSE oidplus demo_iri demo_asn1id demo_ra demo_objects -r ../setup/sql/example_mssql.sql

# Remove database prefix
sed -i 's/`demo_/`/g' ../setup/sql/example_mssql.sql

# Avoid that there is a conflict with well known IDs (e.g. 2.999)
#sed -i 's/INSERT INTO `iri`/INSERT IGNORE INTO `iri`/g' ../setup/sql/example_mssql.sql
#sed -i 's/INSERT INTO `asn1id`/INSERT IGNORE INTO `asn1id`/g' ../setup/sql/example_mssql.sql

# Change `backticks` to [brackets]
sed -iE 's/`\([^`]\+\)`/\[\1\]/g' ../setup/sql/example_mssql.sql

# Change "\n" to "' + CHAR(13) + '"
sed -i "s/\\\n/' \+ CHAR(13) \+ '/g" ../setup/sql/example_mssql.sql

# Change \" to "
sed -i 's/\\"/"/g' ../setup/sql/example_mssql.sql

# Prepend "SET DATEFORMAT ymd;"
echo "SET DATEFORMAT ymd;" > tmp
echo "" >> tmp
cat ../setup/sql/example_mssql.sql >> tmp
cat tmp > ../setup/sql/example_mssql.sql
rm tmp
