#!/usr/bin/php
<?php

require_once __DIR__ . '/../includes/oidplus.inc.php';

OIDplus::init(true);

define('ALL_OID_LIST', '/home/oidplus/all_oids.txt'); // contains all OIDs (non-public file)
define('DESIRED_ROOT', '1.3.6.1.4.1.37476');

# ---

exec("cat ".escapeshellarg(ALL_OID_LIST)." | sort | grep '^".DESIRED_ROOT."'", $out, $ec);

foreach ($out as $oid) {
	$oid = trim($oid);
	if ($oid == '') continue;

	if (strpos($oid, '1.3.6.1.4.1.37476.30.9.') !== 0) check_oid($oid);
}

function check_oid($oid) {

	$res = OIDplus::db()->query("select * from ".OIDPLUS_TABLENAME_PREFIX."objects where id = ?", array("oid:$oid"));
	$ok = $res->num_rows() > 0;

	if (!$ok) {
		echo "Missing at OIDplus: $oid\n";
	}
}

echo "OK\n";
