#!/usr/bin/php
<?php

require_once __DIR__ . '/../oidplus/includes/oidplus.inc.php';

OIDplus::init(false);
if (!defined('OIDINFO_API_URL')) {
	die("OIDINFO_API_URL not available (API is currently not public)\n");
}

OIDplus::db()->set_charset("UTF8");
OIDplus::db()->query("SET NAMES 'utf8'");

define('VERBOSE', false);
define('DEFAULT_EMAIL', 'oidra@viathinksoft.de');
define('ALL_OID_LIST', '/home/oidplus/all_oids.txt'); // contains all OIDs (non-public file)
define('DESIRED_ROOT', '1.3.6.1.4.1.37476');

# ---

exec("cat ".escapeshellarg(ALL_OID_LIST)." | sort | grep '^".DESIRED_ROOT."'", $out, $ec);

foreach ($out as $oid) {
	$oid = trim($oid);
	if ($oid == '') continue;

	check_oid($oid);
}

function check_oid($oid) {

	$res = mysql_query("select * from ".OIDPLUS_TABLENAME_PREFIX."objects where id = 'oid:$oid'");
	$ok = mysql_num_rows($res) > 0;

	if (!$ok) {
		echo "Not existing: $oid : Adding!\n";
		add_oid($oid);
	}
}

echo "OK\n";

# ---

function add_oid($oid, $root=DESIRED_ROOT) {
	if (VERBOSE) echo "Adding $oid ...\n";
	$data = ft_get_oid_data($oid);

	if (!isset($data['oid'])) {
		echo "Warning: Cannot gain information about OID $oid\n";

		$parent = ($oid == $root) ? '' : oid_up($oid);
		$title = '(tbd)';
		$description = '(tbd)';
		$ra_email = '';
		if ((DEFAULT_EMAIL != '') && ($ra_email == '')) $ra_email = DEFAULT_EMAIL;

		$sql = "insert into ".OIDPLUS_TABLENAME_PREFIX."objects (id, parent, title, description, ra_email) values ('oid:".mysql_real_escape_string($oid)."', 'oid:".mysql_real_escape_string($parent)."', '".mysql_real_escape_string($title)."', '".mysql_real_escape_string($description)."', '".mysql_real_escape_string($ra_email)."');";
		sql_execute($sql);

		return;
	}

	if (!isset($data['oid']['identifier'])) $data['oid']['identifier'] = array();
	foreach ($data['oid']['identifier'] as $identifier) {
		$sql = "insert into ".OIDPLUS_TABLENAME_PREFIX."asn1id (oid, name) values ('oid:".mysql_real_escape_string($oid)."', '".mysql_real_escape_string($identifier)."');";
		sql_execute($sql);
	}

	if (!isset($data['oid']['unicode-label'])) $data['oid']['unicode-label'] = array();
	foreach ($data['oid']['unicode-label'] as $identifier) {
		$sql = "insert into ".OIDPLUS_TABLENAME_PREFIX."iri (oid, name) values ('oid:".mysql_real_escape_string($oid)."', '".mysql_real_escape_string($identifier)."');";
		sql_execute($sql);
	}

	$parent = ($oid == $root) ? '' : oid_up($oid);

	$title = strip_tags(@$data['oid']['description']);
	$title = html_entity_decode($title, ENT_COMPAT, 'UTF-8');

	$description = '<strong>' . trim(@$data['oid']['description']) . '</strong><br><br>' . nl2br(trim(@$data['oid']['information']));
	$description = str_replace(array("\r", "\n"), '', $description);
	$description = str_ireplace('<br />', '<br>', $description);
	$description = str_ireplace('<br/>', '<br>', $description);
	$description = '<p>' . str_ireplace('<br><br>', '</p><p>', $description) . '</p>';

	$ra_email = @$data['oid']['current_registrant']['email'];
	if ($ra_email == '') $ra_email = @$data['oid']['first_registrant']['email'];

	$resx = mysql_query("select ra_email from ".OIDPLUS_TABLENAME_PREFIX."objects where id = 'oid:".mysql_real_escape_string($parent)."'");
	if ($rowx = mysql_fetch_array($resx)) $ra_email = $rowx['ra_email'];

	$created = @$data['oid']['first_registrant']['creation-date'];
	$updated = @$data['oid']['last-modification'];

	$sql = "insert into ".OIDPLUS_TABLENAME_PREFIX."objects (id, parent, title, description, ra_email, created, updated) values ('oid:".mysql_real_escape_string($oid)."', 'oid:".mysql_real_escape_string($parent)."', '".mysql_real_escape_string($title)."', '".mysql_real_escape_string($description)."', '".mysql_real_escape_string($ra_email)."', '".mysql_real_escape_string($created)."', '".mysql_real_escape_string($updated)."');";
	sql_execute($sql);
}

function ft_get_oid_data($oid) {
	$url = OIDINFO_API_URL . '&oid='.urlencode($oid);
	$cont_json = @file_get_contents($url);
	if (!$cont_json) {
		sleep(5);
                $cont_json = @file_get_contents($url);
                if (!$cont_json) return false;
	}
	$data = json_decode($cont_json,true);

	return $data;
}

function sql_execute($sql) {
#	echo "$sql\n";
	mysql_query($sql);
	$err = mysql_error();
	if ($err) echo "Warning: $err at $sql\n";
}
