#!/usr/bin/env php
<?php

/*
 * OIDplus 2.0
 * Copyright 2019 - 2021 Daniel Marschall, ViaThinkSoft
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

use ViaThinkSoft\OIDplus\OIDplus;

require_once __DIR__ . '/../includes/oidplus.inc.php';

OIDplus::init(true);

# ---

#$cont = file_get_contents('https://oidplus.viathinksoft.com/oidplus_old/?action=list_all');
$cont = file_get_contents(__DIR__ . '/oidplus_1_with_token.html');

preg_match_all('@oid=\.(.+)">@ismU', $cont, $m);
foreach ($m[1] as $oid) {
	check_oid($oid);
}

/**
 * @param string $oid
 * @return void
 */
function check_oid(string $oid) {

	$res = OIDplus::db()->query("select * from ###objects where id = ?", array("oid:$oid"));
	$ok = $res->num_rows() > 0;

	if (!$ok) {
		echo "Not existing: $oid\n";
	}
}

echo "OK\n";
