#!/usr/bin/php
<?php

require_once __DIR__ . '/../includes/oidplus.inc.php';

OIDplus::init(true);

# ---

#$cont = file_get_contents('https://oidplus.viathinksoft.com/oidplus_old/?action=list_all');
$cont = file_get_contents(__DIR__ . '/oidplus_1_with_token.html');

preg_match_all('@oid=\.(.+)">@ismU', $cont, $m);
foreach ($m[1] as $oid) {
	check_oid($oid);
}

function check_oid($oid) {

	$res = OIDplus::db()->query("select * from ###objects where id = ?", array("oid:$oid"));
	$ok = $res->num_rows() > 0;

	if (!$ok) {
		echo "Not existing: $oid\n";
	}
}

echo "OK\n";
