#!/bin/bash

# OIDplus 2.0
# Copyright 2019 - 2021 Daniel Marschall, ViaThinkSoft
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DIR=$( dirname "$1" )

# 1. Convert everything to DOS except ".svn" and "vendor"
cd "$DIR"/..
mv ".svn" ../_svn
mv "vendor" ../_vendor
find . -type f -exec unix2dos {} \;
mv ../_svn ".svn"
mv ../_vendor "vendor"

# 2. Convert Linux shell script back to Unix format
dos2unix plugins/publicPages/100_whois/whois/cli/whois

cd dev
find . -type f -exec dos2unix {} \;

# 3. But this single PHP file in "dev/test" can be DOS
cd test
unix2dos test_database_plugins.php
