#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hit.Core.Datenbank
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OIDDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void Insertoidplus_asn1id(oidplus_asn1id instance);
    partial void Updateoidplus_asn1id(oidplus_asn1id instance);
    partial void Deleteoidplus_asn1id(oidplus_asn1id instance);
    partial void Insertoidplus_ra(oidplus_ra instance);
    partial void Updateoidplus_ra(oidplus_ra instance);
    partial void Deleteoidplus_ra(oidplus_ra instance);
    partial void Insertoidplus_config(oidplus_config instance);
    partial void Updateoidplus_config(oidplus_config instance);
    partial void Deleteoidplus_config(oidplus_config instance);
    partial void Insertoidplus_iri(oidplus_iri instance);
    partial void Updateoidplus_iri(oidplus_iri instance);
    partial void Deleteoidplus_iri(oidplus_iri instance);
    partial void Insertoidplus_log(oidplus_log instance);
    partial void Updateoidplus_log(oidplus_log instance);
    partial void Deleteoidplus_log(oidplus_log instance);
    partial void Insertoidplus_log_object(oidplus_log_object instance);
    partial void Updateoidplus_log_object(oidplus_log_object instance);
    partial void Deleteoidplus_log_object(oidplus_log_object instance);
    partial void Insertoidplus_log_user(oidplus_log_user instance);
    partial void Updateoidplus_log_user(oidplus_log_user instance);
    partial void Deleteoidplus_log_user(oidplus_log_user instance);
    partial void Insertoidplus_objects(oidplus_objects instance);
    partial void Updateoidplus_objects(oidplus_objects instance);
    partial void Deleteoidplus_objects(oidplus_objects instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::hit.Core.Properties.Settings.Default.OIDDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<oidplus_asn1id> oidplus_asn1id
		{
			get
			{
				return this.GetTable<oidplus_asn1id>();
			}
		}
		
		public System.Data.Linq.Table<oidplus_ra> oidplus_ra
		{
			get
			{
				return this.GetTable<oidplus_ra>();
			}
		}
		
		public System.Data.Linq.Table<oidplus_config> oidplus_config
		{
			get
			{
				return this.GetTable<oidplus_config>();
			}
		}
		
		public System.Data.Linq.Table<oidplus_iri> oidplus_iri
		{
			get
			{
				return this.GetTable<oidplus_iri>();
			}
		}
		
		public System.Data.Linq.Table<oidplus_log> oidplus_log
		{
			get
			{
				return this.GetTable<oidplus_log>();
			}
		}
		
		public System.Data.Linq.Table<oidplus_log_object> oidplus_log_object
		{
			get
			{
				return this.GetTable<oidplus_log_object>();
			}
		}
		
		public System.Data.Linq.Table<oidplus_log_user> oidplus_log_user
		{
			get
			{
				return this.GetTable<oidplus_log_user>();
			}
		}
		
		public System.Data.Linq.Table<oidplus_objects> oidplus_objects
		{
			get
			{
				return this.GetTable<oidplus_objects>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oidplus_asn1id")]
	public partial class oidplus_asn1id : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _lfd;
		
		private string _oid;
		
		private string _name;
		
		private bool _standardized;
		
		private bool _well_known;
		
		private EntityRef<oidplus_objects> _oidplus_objects;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlfdChanging(int value);
    partial void OnlfdChanged();
    partial void OnoidChanging(string value);
    partial void OnoidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnstandardizedChanging(bool value);
    partial void OnstandardizedChanged();
    partial void Onwell_knownChanging(bool value);
    partial void Onwell_knownChanged();
    #endregion
		
		public oidplus_asn1id()
		{
			this._oidplus_objects = default(EntityRef<oidplus_objects>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lfd", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int lfd
		{
			get
			{
				return this._lfd;
			}
			set
			{
				if ((this._lfd != value))
				{
					this.OnlfdChanging(value);
					this.SendPropertyChanging();
					this._lfd = value;
					this.SendPropertyChanged("lfd");
					this.OnlfdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oid", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string oid
		{
			get
			{
				return this._oid;
			}
			set
			{
				if ((this._oid != value))
				{
					if (this._oidplus_objects.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnoidChanging(value);
					this.SendPropertyChanging();
					this._oid = value;
					this.SendPropertyChanged("oid");
					this.OnoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_standardized", DbType="Bit NOT NULL")]
		public bool standardized
		{
			get
			{
				return this._standardized;
			}
			set
			{
				if ((this._standardized != value))
				{
					this.OnstandardizedChanging(value);
					this.SendPropertyChanging();
					this._standardized = value;
					this.SendPropertyChanged("standardized");
					this.OnstandardizedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_well_known", DbType="Bit NOT NULL")]
		public bool well_known
		{
			get
			{
				return this._well_known;
			}
			set
			{
				if ((this._well_known != value))
				{
					this.Onwell_knownChanging(value);
					this.SendPropertyChanging();
					this._well_known = value;
					this.SendPropertyChanged("well_known");
					this.Onwell_knownChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_objects_oidplus_asn1id", Storage="_oidplus_objects", ThisKey="oid", OtherKey="id", IsForeignKey=true)]
		public oidplus_objects oidplus_objects
		{
			get
			{
				return this._oidplus_objects.Entity;
			}
			set
			{
				oidplus_objects previousValue = this._oidplus_objects.Entity;
				if (((previousValue != value) 
							|| (this._oidplus_objects.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oidplus_objects.Entity = null;
						previousValue.oidplus_asn1id.Remove(this);
					}
					this._oidplus_objects.Entity = value;
					if ((value != null))
					{
						value.oidplus_asn1id.Add(this);
						this._oid = value.id;
					}
					else
					{
						this._oid = default(string);
					}
					this.SendPropertyChanged("oidplus_objects");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oidplus_ra")]
	public partial class oidplus_ra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ra_id;
		
		private string _email;
		
		private string _ra_name;
		
		private string _personal_name;
		
		private string _organization;
		
		private string _office;
		
		private string _street;
		
		private string _zip_town;
		
		private string _country;
		
		private string _phone;
		
		private string _mobile;
		
		private string _fax;
		
		private bool _privacy;
		
		private string _salt;
		
		private string _authkey;
		
		private System.Nullable<System.DateTime> _registered;
		
		private System.Nullable<System.DateTime> _updated;
		
		private System.Nullable<System.DateTime> _last_login;
		
		private EntitySet<oidplus_objects> _oidplus_objects;
		
		private EntitySet<oidplus_log_user> _oidplus_log_user;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onra_idChanging(int value);
    partial void Onra_idChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onra_nameChanging(string value);
    partial void Onra_nameChanged();
    partial void Onpersonal_nameChanging(string value);
    partial void Onpersonal_nameChanged();
    partial void OnorganizationChanging(string value);
    partial void OnorganizationChanged();
    partial void OnofficeChanging(string value);
    partial void OnofficeChanged();
    partial void OnstreetChanging(string value);
    partial void OnstreetChanged();
    partial void Onzip_townChanging(string value);
    partial void Onzip_townChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnprivacyChanging(bool value);
    partial void OnprivacyChanged();
    partial void OnsaltChanging(string value);
    partial void OnsaltChanged();
    partial void OnauthkeyChanging(string value);
    partial void OnauthkeyChanged();
    partial void OnregisteredChanging(System.Nullable<System.DateTime> value);
    partial void OnregisteredChanged();
    partial void OnupdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedChanged();
    partial void Onlast_loginChanging(System.Nullable<System.DateTime> value);
    partial void Onlast_loginChanged();
    #endregion
		
		public oidplus_ra()
		{
			this._oidplus_objects = new EntitySet<oidplus_objects>(new Action<oidplus_objects>(this.attach_oidplus_objects), new Action<oidplus_objects>(this.detach_oidplus_objects));
			this._oidplus_log_user = new EntitySet<oidplus_log_user>(new Action<oidplus_log_user>(this.attach_oidplus_log_user), new Action<oidplus_log_user>(this.detach_oidplus_log_user));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ra_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ra_id
		{
			get
			{
				return this._ra_id;
			}
			set
			{
				if ((this._ra_id != value))
				{
					this.Onra_idChanging(value);
					this.SendPropertyChanging();
					this._ra_id = value;
					this.SendPropertyChanged("ra_id");
					this.Onra_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ra_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ra_name
		{
			get
			{
				return this._ra_name;
			}
			set
			{
				if ((this._ra_name != value))
				{
					this.Onra_nameChanging(value);
					this.SendPropertyChanging();
					this._ra_name = value;
					this.SendPropertyChanged("ra_name");
					this.Onra_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personal_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string personal_name
		{
			get
			{
				return this._personal_name;
			}
			set
			{
				if ((this._personal_name != value))
				{
					this.Onpersonal_nameChanging(value);
					this.SendPropertyChanging();
					this._personal_name = value;
					this.SendPropertyChanged("personal_name");
					this.Onpersonal_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organization", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string organization
		{
			get
			{
				return this._organization;
			}
			set
			{
				if ((this._organization != value))
				{
					this.OnorganizationChanging(value);
					this.SendPropertyChanging();
					this._organization = value;
					this.SendPropertyChanged("organization");
					this.OnorganizationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_office", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string office
		{
			get
			{
				return this._office;
			}
			set
			{
				if ((this._office != value))
				{
					this.OnofficeChanging(value);
					this.SendPropertyChanging();
					this._office = value;
					this.SendPropertyChanged("office");
					this.OnofficeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string street
		{
			get
			{
				return this._street;
			}
			set
			{
				if ((this._street != value))
				{
					this.OnstreetChanging(value);
					this.SendPropertyChanging();
					this._street = value;
					this.SendPropertyChanged("street");
					this.OnstreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip_town", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string zip_town
		{
			get
			{
				return this._zip_town;
			}
			set
			{
				if ((this._zip_town != value))
				{
					this.Onzip_townChanging(value);
					this.SendPropertyChanging();
					this._zip_town = value;
					this.SendPropertyChanged("zip_town");
					this.Onzip_townChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_privacy", DbType="Bit NOT NULL")]
		public bool privacy
		{
			get
			{
				return this._privacy;
			}
			set
			{
				if ((this._privacy != value))
				{
					this.OnprivacyChanging(value);
					this.SendPropertyChanging();
					this._privacy = value;
					this.SendPropertyChanged("privacy");
					this.OnprivacyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salt", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string salt
		{
			get
			{
				return this._salt;
			}
			set
			{
				if ((this._salt != value))
				{
					this.OnsaltChanging(value);
					this.SendPropertyChanging();
					this._salt = value;
					this.SendPropertyChanged("salt");
					this.OnsaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_authkey", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string authkey
		{
			get
			{
				return this._authkey;
			}
			set
			{
				if ((this._authkey != value))
				{
					this.OnauthkeyChanging(value);
					this.SendPropertyChanging();
					this._authkey = value;
					this.SendPropertyChanged("authkey");
					this.OnauthkeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registered", DbType="DateTime")]
		public System.Nullable<System.DateTime> registered
		{
			get
			{
				return this._registered;
			}
			set
			{
				if ((this._registered != value))
				{
					this.OnregisteredChanging(value);
					this.SendPropertyChanging();
					this._registered = value;
					this.SendPropertyChanged("registered");
					this.OnregisteredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated
		{
			get
			{
				return this._updated;
			}
			set
			{
				if ((this._updated != value))
				{
					this.OnupdatedChanging(value);
					this.SendPropertyChanging();
					this._updated = value;
					this.SendPropertyChanged("updated");
					this.OnupdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_login", DbType="DateTime")]
		public System.Nullable<System.DateTime> last_login
		{
			get
			{
				return this._last_login;
			}
			set
			{
				if ((this._last_login != value))
				{
					this.Onlast_loginChanging(value);
					this.SendPropertyChanging();
					this._last_login = value;
					this.SendPropertyChanged("last_login");
					this.Onlast_loginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_ra_oidplus_objects", Storage="_oidplus_objects", ThisKey="email", OtherKey="ra_email")]
		public EntitySet<oidplus_objects> oidplus_objects
		{
			get
			{
				return this._oidplus_objects;
			}
			set
			{
				this._oidplus_objects.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_ra_oidplus_log_user", Storage="_oidplus_log_user", ThisKey="email", OtherKey="username")]
		public EntitySet<oidplus_log_user> oidplus_log_user
		{
			get
			{
				return this._oidplus_log_user;
			}
			set
			{
				this._oidplus_log_user.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_oidplus_objects(oidplus_objects entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_ra = this;
		}
		
		private void detach_oidplus_objects(oidplus_objects entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_ra = null;
		}
		
		private void attach_oidplus_log_user(oidplus_log_user entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_ra = this;
		}
		
		private void detach_oidplus_log_user(oidplus_log_user entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_ra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oidplus_config")]
	public partial class oidplus_config : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private string _value;
		
		private string _description;
		
		private bool _protected;
		
		private bool _visible;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnprotectedChanging(bool value);
    partial void OnprotectedChanged();
    partial void OnvisibleChanging(bool value);
    partial void OnvisibleChanged();
    #endregion
		
		public oidplus_config()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(255)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="protected", Storage="_protected", DbType="Bit NOT NULL")]
		public bool @protected
		{
			get
			{
				return this._protected;
			}
			set
			{
				if ((this._protected != value))
				{
					this.OnprotectedChanging(value);
					this.SendPropertyChanging();
					this._protected = value;
					this.SendPropertyChanged("@protected");
					this.OnprotectedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visible", DbType="Bit NOT NULL")]
		public bool visible
		{
			get
			{
				return this._visible;
			}
			set
			{
				if ((this._visible != value))
				{
					this.OnvisibleChanging(value);
					this.SendPropertyChanging();
					this._visible = value;
					this.SendPropertyChanged("visible");
					this.OnvisibleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oidplus_iri")]
	public partial class oidplus_iri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _lfd;
		
		private string _oid;
		
		private string _name;
		
		private bool _longarc;
		
		private bool _well_known;
		
		private EntityRef<oidplus_objects> _oidplus_objects;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlfdChanging(int value);
    partial void OnlfdChanged();
    partial void OnoidChanging(string value);
    partial void OnoidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnlongarcChanging(bool value);
    partial void OnlongarcChanged();
    partial void Onwell_knownChanging(bool value);
    partial void Onwell_knownChanged();
    #endregion
		
		public oidplus_iri()
		{
			this._oidplus_objects = default(EntityRef<oidplus_objects>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lfd", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int lfd
		{
			get
			{
				return this._lfd;
			}
			set
			{
				if ((this._lfd != value))
				{
					this.OnlfdChanging(value);
					this.SendPropertyChanging();
					this._lfd = value;
					this.SendPropertyChanged("lfd");
					this.OnlfdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oid", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string oid
		{
			get
			{
				return this._oid;
			}
			set
			{
				if ((this._oid != value))
				{
					if (this._oidplus_objects.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnoidChanging(value);
					this.SendPropertyChanging();
					this._oid = value;
					this.SendPropertyChanged("oid");
					this.OnoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longarc", DbType="Bit NOT NULL")]
		public bool longarc
		{
			get
			{
				return this._longarc;
			}
			set
			{
				if ((this._longarc != value))
				{
					this.OnlongarcChanging(value);
					this.SendPropertyChanging();
					this._longarc = value;
					this.SendPropertyChanged("longarc");
					this.OnlongarcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_well_known", DbType="Bit NOT NULL")]
		public bool well_known
		{
			get
			{
				return this._well_known;
			}
			set
			{
				if ((this._well_known != value))
				{
					this.Onwell_knownChanging(value);
					this.SendPropertyChanging();
					this._well_known = value;
					this.SendPropertyChanged("well_known");
					this.Onwell_knownChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_objects_oidplus_iri", Storage="_oidplus_objects", ThisKey="oid", OtherKey="id", IsForeignKey=true)]
		public oidplus_objects oidplus_objects
		{
			get
			{
				return this._oidplus_objects.Entity;
			}
			set
			{
				oidplus_objects previousValue = this._oidplus_objects.Entity;
				if (((previousValue != value) 
							|| (this._oidplus_objects.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oidplus_objects.Entity = null;
						previousValue.oidplus_iri.Remove(this);
					}
					this._oidplus_objects.Entity = value;
					if ((value != null))
					{
						value.oidplus_iri.Add(this);
						this._oid = value.id;
					}
					else
					{
						this._oid = default(string);
					}
					this.SendPropertyChanged("oidplus_objects");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oidplus_log")]
	public partial class oidplus_log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private long _unix_ts;
		
		private string _addr;
		
		private string _event;
		
		private EntityRef<oidplus_log_user> _oidplus_log_user1;
		
		private EntityRef<oidplus_log_object> _oidplus_log_object;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onunix_tsChanging(long value);
    partial void Onunix_tsChanged();
    partial void OnaddrChanging(string value);
    partial void OnaddrChanged();
    partial void OneventChanging(string value);
    partial void OneventChanged();
    #endregion
		
		public oidplus_log()
		{
			this._oidplus_log_user1 = default(EntityRef<oidplus_log_user>);
			this._oidplus_log_object = default(EntityRef<oidplus_log_object>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					if ((this._oidplus_log_user1.HasLoadedOrAssignedValue || this._oidplus_log_object.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unix_ts", DbType="BigInt NOT NULL")]
		public long unix_ts
		{
			get
			{
				return this._unix_ts;
			}
			set
			{
				if ((this._unix_ts != value))
				{
					this.Onunix_tsChanging(value);
					this.SendPropertyChanging();
					this._unix_ts = value;
					this.SendPropertyChanged("unix_ts");
					this.Onunix_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addr", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string addr
		{
			get
			{
				return this._addr;
			}
			set
			{
				if ((this._addr != value))
				{
					this.OnaddrChanging(value);
					this.SendPropertyChanging();
					this._addr = value;
					this.SendPropertyChanged("addr");
					this.OnaddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="event", Storage="_event", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string @event
		{
			get
			{
				return this._event;
			}
			set
			{
				if ((this._event != value))
				{
					this.OneventChanging(value);
					this.SendPropertyChanging();
					this._event = value;
					this.SendPropertyChanged("@event");
					this.OneventChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_log_user_oidplus_log", Storage="_oidplus_log_user1", ThisKey="id", OtherKey="log_id", IsForeignKey=true)]
		public oidplus_log_user oidplus_log_user1
		{
			get
			{
				return this._oidplus_log_user1.Entity;
			}
			set
			{
				oidplus_log_user previousValue = this._oidplus_log_user1.Entity;
				if (((previousValue != value) 
							|| (this._oidplus_log_user1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oidplus_log_user1.Entity = null;
						previousValue.oidplus_log1.Remove(this);
					}
					this._oidplus_log_user1.Entity = value;
					if ((value != null))
					{
						value.oidplus_log1.Add(this);
						this._id = value.log_id;
					}
					else
					{
						this._id = default(int);
					}
					this.SendPropertyChanged("oidplus_log_user1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_log_object_oidplus_log", Storage="_oidplus_log_object", ThisKey="id", OtherKey="log_id", IsForeignKey=true)]
		public oidplus_log_object oidplus_log_object
		{
			get
			{
				return this._oidplus_log_object.Entity;
			}
			set
			{
				oidplus_log_object previousValue = this._oidplus_log_object.Entity;
				if (((previousValue != value) 
							|| (this._oidplus_log_object.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oidplus_log_object.Entity = null;
						previousValue.oidplus_log.Remove(this);
					}
					this._oidplus_log_object.Entity = value;
					if ((value != null))
					{
						value.oidplus_log.Add(this);
						this._id = value.log_id;
					}
					else
					{
						this._id = default(int);
					}
					this.SendPropertyChanged("oidplus_log_object");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oidplus_log_object")]
	public partial class oidplus_log_object : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _log_id;
		
		private string _object;
		
		private int _severity;
		
		private EntitySet<oidplus_log> _oidplus_log;
		
		private EntityRef<oidplus_objects> _oidplus_objects;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onlog_idChanging(int value);
    partial void Onlog_idChanged();
    partial void OnobjectChanging(string value);
    partial void OnobjectChanged();
    partial void OnseverityChanging(int value);
    partial void OnseverityChanged();
    #endregion
		
		public oidplus_log_object()
		{
			this._oidplus_log = new EntitySet<oidplus_log>(new Action<oidplus_log>(this.attach_oidplus_log), new Action<oidplus_log>(this.detach_oidplus_log));
			this._oidplus_objects = default(EntityRef<oidplus_objects>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", DbType="Int NOT NULL")]
		public int log_id
		{
			get
			{
				return this._log_id;
			}
			set
			{
				if ((this._log_id != value))
				{
					this.Onlog_idChanging(value);
					this.SendPropertyChanging();
					this._log_id = value;
					this.SendPropertyChanged("log_id");
					this.Onlog_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="object", Storage="_object", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string @object
		{
			get
			{
				return this._object;
			}
			set
			{
				if ((this._object != value))
				{
					if (this._oidplus_objects.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnobjectChanging(value);
					this.SendPropertyChanging();
					this._object = value;
					this.SendPropertyChanged("@object");
					this.OnobjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_severity", DbType="Int NOT NULL")]
		public int severity
		{
			get
			{
				return this._severity;
			}
			set
			{
				if ((this._severity != value))
				{
					this.OnseverityChanging(value);
					this.SendPropertyChanging();
					this._severity = value;
					this.SendPropertyChanged("severity");
					this.OnseverityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_log_object_oidplus_log", Storage="_oidplus_log", ThisKey="log_id", OtherKey="id")]
		public EntitySet<oidplus_log> oidplus_log
		{
			get
			{
				return this._oidplus_log;
			}
			set
			{
				this._oidplus_log.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_objects_oidplus_log_object", Storage="_oidplus_objects", ThisKey="object", OtherKey="id", IsForeignKey=true)]
		public oidplus_objects oidplus_objects
		{
			get
			{
				return this._oidplus_objects.Entity;
			}
			set
			{
				oidplus_objects previousValue = this._oidplus_objects.Entity;
				if (((previousValue != value) 
							|| (this._oidplus_objects.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oidplus_objects.Entity = null;
						previousValue.oidplus_log_object.Remove(this);
					}
					this._oidplus_objects.Entity = value;
					if ((value != null))
					{
						value.oidplus_log_object.Add(this);
						this._object = value.id;
					}
					else
					{
						this._object = default(string);
					}
					this.SendPropertyChanged("oidplus_objects");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_oidplus_log(oidplus_log entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_log_object = this;
		}
		
		private void detach_oidplus_log(oidplus_log entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_log_object = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oidplus_log_user")]
	public partial class oidplus_log_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _log_id;
		
		private string _username;
		
		private int _severity;
		
		private EntitySet<oidplus_log> _oidplus_log1;
		
		private EntityRef<oidplus_ra> _oidplus_ra;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onlog_idChanging(int value);
    partial void Onlog_idChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnseverityChanging(int value);
    partial void OnseverityChanged();
    #endregion
		
		public oidplus_log_user()
		{
			this._oidplus_log1 = new EntitySet<oidplus_log>(new Action<oidplus_log>(this.attach_oidplus_log1), new Action<oidplus_log>(this.detach_oidplus_log1));
			this._oidplus_ra = default(EntityRef<oidplus_ra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", DbType="Int NOT NULL")]
		public int log_id
		{
			get
			{
				return this._log_id;
			}
			set
			{
				if ((this._log_id != value))
				{
					this.Onlog_idChanging(value);
					this.SendPropertyChanging();
					this._log_id = value;
					this.SendPropertyChanged("log_id");
					this.Onlog_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					if (this._oidplus_ra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_severity", DbType="Int NOT NULL")]
		public int severity
		{
			get
			{
				return this._severity;
			}
			set
			{
				if ((this._severity != value))
				{
					this.OnseverityChanging(value);
					this.SendPropertyChanging();
					this._severity = value;
					this.SendPropertyChanged("severity");
					this.OnseverityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_log_user_oidplus_log", Storage="_oidplus_log1", ThisKey="log_id", OtherKey="id")]
		public EntitySet<oidplus_log> oidplus_log1
		{
			get
			{
				return this._oidplus_log1;
			}
			set
			{
				this._oidplus_log1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_ra_oidplus_log_user", Storage="_oidplus_ra", ThisKey="username", OtherKey="email", IsForeignKey=true)]
		public oidplus_ra oidplus_ra
		{
			get
			{
				return this._oidplus_ra.Entity;
			}
			set
			{
				oidplus_ra previousValue = this._oidplus_ra.Entity;
				if (((previousValue != value) 
							|| (this._oidplus_ra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oidplus_ra.Entity = null;
						previousValue.oidplus_log_user.Remove(this);
					}
					this._oidplus_ra.Entity = value;
					if ((value != null))
					{
						value.oidplus_log_user.Add(this);
						this._username = value.email;
					}
					else
					{
						this._username = default(string);
					}
					this.SendPropertyChanged("oidplus_ra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_oidplus_log1(oidplus_log entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_log_user1 = this;
		}
		
		private void detach_oidplus_log1(oidplus_log entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_log_user1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oidplus_objects")]
	public partial class oidplus_objects : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _parent;
		
		private string _title;
		
		private string _description;
		
		private string _ra_email;
		
		private bool _confidential;
		
		private System.Nullable<System.DateTime> _created;
		
		private System.Nullable<System.DateTime> _updated;
		
		private string _comment;
		
		private EntitySet<oidplus_objects> _oidplus_objects2;
		
		private EntitySet<oidplus_asn1id> _oidplus_asn1id;
		
		private EntitySet<oidplus_iri> _oidplus_iri;
		
		private EntitySet<oidplus_log_object> _oidplus_log_object;
		
		private EntityRef<oidplus_ra> _oidplus_ra;
		
		private EntityRef<oidplus_objects> _oidplus_objects1;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnparentChanging(string value);
    partial void OnparentChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onra_emailChanging(string value);
    partial void Onra_emailChanged();
    partial void OnconfidentialChanging(bool value);
    partial void OnconfidentialChanged();
    partial void OncreatedChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedChanged();
    partial void OnupdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    #endregion
		
		public oidplus_objects()
		{
			this._oidplus_objects2 = new EntitySet<oidplus_objects>(new Action<oidplus_objects>(this.attach_oidplus_objects2), new Action<oidplus_objects>(this.detach_oidplus_objects2));
			this._oidplus_asn1id = new EntitySet<oidplus_asn1id>(new Action<oidplus_asn1id>(this.attach_oidplus_asn1id), new Action<oidplus_asn1id>(this.detach_oidplus_asn1id));
			this._oidplus_iri = new EntitySet<oidplus_iri>(new Action<oidplus_iri>(this.attach_oidplus_iri), new Action<oidplus_iri>(this.detach_oidplus_iri));
			this._oidplus_log_object = new EntitySet<oidplus_log_object>(new Action<oidplus_log_object>(this.attach_oidplus_log_object), new Action<oidplus_log_object>(this.detach_oidplus_log_object));
			this._oidplus_ra = default(EntityRef<oidplus_ra>);
			this._oidplus_objects1 = default(EntityRef<oidplus_objects>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent", DbType="VarChar(255)")]
		public string parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					if (this._oidplus_objects1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnparentChanging(value);
					this.SendPropertyChanging();
					this._parent = value;
					this.SendPropertyChanged("parent");
					this.OnparentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ra_email", DbType="VarChar(100)")]
		public string ra_email
		{
			get
			{
				return this._ra_email;
			}
			set
			{
				if ((this._ra_email != value))
				{
					if (this._oidplus_ra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onra_emailChanging(value);
					this.SendPropertyChanging();
					this._ra_email = value;
					this.SendPropertyChanged("ra_email");
					this.Onra_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_confidential", DbType="Bit NOT NULL")]
		public bool confidential
		{
			get
			{
				return this._confidential;
			}
			set
			{
				if ((this._confidential != value))
				{
					this.OnconfidentialChanging(value);
					this.SendPropertyChanging();
					this._confidential = value;
					this.SendPropertyChanged("confidential");
					this.OnconfidentialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created", DbType="DateTime")]
		public System.Nullable<System.DateTime> created
		{
			get
			{
				return this._created;
			}
			set
			{
				if ((this._created != value))
				{
					this.OncreatedChanging(value);
					this.SendPropertyChanging();
					this._created = value;
					this.SendPropertyChanged("created");
					this.OncreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated
		{
			get
			{
				return this._updated;
			}
			set
			{
				if ((this._updated != value))
				{
					this.OnupdatedChanging(value);
					this.SendPropertyChanging();
					this._updated = value;
					this.SendPropertyChanged("updated");
					this.OnupdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="VarChar(255)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_objects_oidplus_objects", Storage="_oidplus_objects2", ThisKey="id", OtherKey="parent")]
		public EntitySet<oidplus_objects> oidplus_objects2
		{
			get
			{
				return this._oidplus_objects2;
			}
			set
			{
				this._oidplus_objects2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_objects_oidplus_asn1id", Storage="_oidplus_asn1id", ThisKey="id", OtherKey="oid")]
		public EntitySet<oidplus_asn1id> oidplus_asn1id
		{
			get
			{
				return this._oidplus_asn1id;
			}
			set
			{
				this._oidplus_asn1id.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_objects_oidplus_iri", Storage="_oidplus_iri", ThisKey="id", OtherKey="oid")]
		public EntitySet<oidplus_iri> oidplus_iri
		{
			get
			{
				return this._oidplus_iri;
			}
			set
			{
				this._oidplus_iri.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_objects_oidplus_log_object", Storage="_oidplus_log_object", ThisKey="id", OtherKey="object")]
		public EntitySet<oidplus_log_object> oidplus_log_object
		{
			get
			{
				return this._oidplus_log_object;
			}
			set
			{
				this._oidplus_log_object.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_ra_oidplus_objects", Storage="_oidplus_ra", ThisKey="ra_email", OtherKey="email", IsForeignKey=true)]
		public oidplus_ra oidplus_ra
		{
			get
			{
				return this._oidplus_ra.Entity;
			}
			set
			{
				oidplus_ra previousValue = this._oidplus_ra.Entity;
				if (((previousValue != value) 
							|| (this._oidplus_ra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oidplus_ra.Entity = null;
						previousValue.oidplus_objects.Remove(this);
					}
					this._oidplus_ra.Entity = value;
					if ((value != null))
					{
						value.oidplus_objects.Add(this);
						this._ra_email = value.email;
					}
					else
					{
						this._ra_email = default(string);
					}
					this.SendPropertyChanged("oidplus_ra");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="oidplus_objects_oidplus_objects", Storage="_oidplus_objects1", ThisKey="parent", OtherKey="id", IsForeignKey=true)]
		public oidplus_objects oidplus_objects1
		{
			get
			{
				return this._oidplus_objects1.Entity;
			}
			set
			{
				oidplus_objects previousValue = this._oidplus_objects1.Entity;
				if (((previousValue != value) 
							|| (this._oidplus_objects1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oidplus_objects1.Entity = null;
						previousValue.oidplus_objects2.Remove(this);
					}
					this._oidplus_objects1.Entity = value;
					if ((value != null))
					{
						value.oidplus_objects2.Add(this);
						this._parent = value.id;
					}
					else
					{
						this._parent = default(string);
					}
					this.SendPropertyChanged("oidplus_objects1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_oidplus_objects2(oidplus_objects entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_objects1 = this;
		}
		
		private void detach_oidplus_objects2(oidplus_objects entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_objects1 = null;
		}
		
		private void attach_oidplus_asn1id(oidplus_asn1id entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_objects = this;
		}
		
		private void detach_oidplus_asn1id(oidplus_asn1id entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_objects = null;
		}
		
		private void attach_oidplus_iri(oidplus_iri entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_objects = this;
		}
		
		private void detach_oidplus_iri(oidplus_iri entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_objects = null;
		}
		
		private void attach_oidplus_log_object(oidplus_log_object entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_objects = this;
		}
		
		private void detach_oidplus_log_object(oidplus_log_object entity)
		{
			this.SendPropertyChanging();
			entity.oidplus_objects = null;
		}
	}
}
#pragma warning restore 1591
