-- We have the same problem like in Oracle in re upper/lower-case:
-- config means CONFIG,
-- "config" means config
-- Since we use config in the code, we must use "CONFIG" here


-- You can import this file using the iSQL Tool command:
-- "C:\Program Files\Firebird\Firebird_3_0\isql.exe" -z -i "d:\SVN\OIDplus\trunk\setup\sql\struct_firebird.sql"
-- (Change the file paths)


-- Connect to the database
-- PLEASE CHANGE THE PATH HERE, BEFORE PASSING THE FILE TO iSQL Tool
connect 'D:\SVN\OIDplus\trunk\userdata\database\oidplus.fdb' user 'SYSDBA' password 'masterkey';


recreate table "CONFIG" (
  "NAME" varchar(50) CHARACTER SET UNICODE_FSS NOT NULL,
  "VALUE" BLOB SUB_TYPE TEXT NOT NULL,
  "DESCRIPTION" varchar(255) CHARACTER SET UNICODE_FSS,
  "PROTECTED" char(1) DEFAULT '0' NOT NULL,
  "VISIBLE" char(1) DEFAULT '0' NOT NULL,
  constraint "PK_CONFIG" primary key ("NAME")
);

/* -------------------------------------------------- */

recreate table "ASN1ID" (
  "LFD" integer generated by default as identity,
  "OID" varchar(255) CHARACTER SET UNICODE_FSS NOT NULL,
  "NAME" varchar(255) CHARACTER SET UNICODE_FSS NOT NULL,
  "STANDARDIZED" char(1) DEFAULT '0' NOT NULL,
  "WELL_KNOWN" char(1) DEFAULT '0' NOT NULL,
  constraint "PK_ASN1ID" primary key ("LFD"),
  constraint "UK_ASN1ID_1" unique ("OID","NAME")
);

/* -------------------------------------------------- */

recreate table "IRI" (
  "LFD" integer generated by default as identity,
  "OID" varchar(255) CHARACTER SET UNICODE_FSS NOT NULL,
  "NAME" varchar(255) CHARACTER SET UNICODE_FSS NOT NULL,
  "LONGARC" char(1) DEFAULT '0' NOT NULL,
  "WELL_KNOWN" char(1) DEFAULT '0' NOT NULL,
  constraint "PK_IRI" primary key ("LFD"),
  constraint "UK_IRI_1" unique ("OID","NAME")
);

/* -------------------------------------------------- */

recreate table "OBJECTS" (
  "ID" varchar(255) CHARACTER SET UNICODE_FSS NOT NULL,
  "PARENT" varchar(255) CHARACTER SET UNICODE_FSS,
  "TITLE" varchar(255) CHARACTER SET UNICODE_FSS,
  "DESCRIPTION" BLOB SUB_TYPE TEXT,
  "RA_EMAIL" varchar(100) CHARACTER SET UNICODE_FSS,
  "CONFIDENTIAL" char(1) NOT NULL,
  "CREATED" timestamp,
  "UPDATED" timestamp,
  "COMMENT" varchar(255) CHARACTER SET UNICODE_FSS,
  constraint "PK_OBJECTS" primary key ("ID")
);

/* -------------------------------------------------- */

recreate table "RA" (
  "RA_ID" integer generated by default as identity,
  "EMAIL" varchar(100) CHARACTER SET UNICODE_FSS NOT NULL,
  "RA_NAME" varchar(100) CHARACTER SET UNICODE_FSS,
  "PERSONAL_NAME" varchar(100) CHARACTER SET UNICODE_FSS,
  "ORGANIZATION" varchar(100) CHARACTER SET UNICODE_FSS,
  "OFFICE" varchar(100) CHARACTER SET UNICODE_FSS,
  "STREET" varchar(100) CHARACTER SET UNICODE_FSS,
  "ZIP_TOWN" varchar(100) CHARACTER SET UNICODE_FSS,
  "COUNTRY" varchar(100) CHARACTER SET UNICODE_FSS,
  "PHONE" varchar(100) CHARACTER SET UNICODE_FSS,
  "MOBILE" varchar(100) CHARACTER SET UNICODE_FSS,
  "FAX" varchar(100) CHARACTER SET UNICODE_FSS,
  "PRIVACY" char(1) DEFAULT '0' NOT NULL,
  "AUTHKEY" varchar(250) CHARACTER SET UNICODE_FSS,
  "REGISTERED" timestamp,
  "UPDATED" timestamp,
  "LAST_LOGIN" timestamp,
  constraint "PK_RA" primary key ("RA_ID"),
  constraint "UK_RA_1" unique ("EMAIL")
);

/* -------------------------------------------------- */

recreate table "LOG" (
  "ID" integer generated by default as identity,
  "UNIX_TS" bigint NOT NULL,
  "ADDR" varchar(45) CHARACTER SET UNICODE_FSS NOT NULL,
  "EVENT" BLOB SUB_TYPE TEXT NOT NULL,
  constraint "PK_LOG" primary key ("ID")
);

/* -------------------------------------------------- */

recreate table "LOG_USER" (
  "ID" integer generated by default as identity,
  "LOG_ID" integer NOT NULL,
  "USERNAME" varchar(255) CHARACTER SET UNICODE_FSS NOT NULL,
  "SEVERITY" integer NOT NULL,
  constraint "PK_LOG_USER" primary key ("ID"),
  constraint "UK_LOG_USER_1" unique ("LOG_ID","USERNAME")
);

/* -------------------------------------------------- */

recreate table "LOG_OBJECT" (
  "ID" integer generated by default as identity,
  "LOG_ID" integer NOT NULL,
  "OBJECT" varchar(255) CHARACTER SET UNICODE_FSS NOT NULL,
  "SEVERITY" integer NOT NULL,
  constraint "PK_LOG_OBJECT" primary key ("ID"),
  constraint "UK_LOG_OBJECT_1" unique ("LOG_ID","OBJECT")
);

/* -------------------------------------------------- */

INSERT INTO "CONFIG" ("NAME", "DESCRIPTION", "VALUE", "PROTECTED", "VISIBLE") VALUES ('database_version', 'Version of the database tables', '1002', '1', '0');


-- Quit = exit and rollback changes!
-- Exit = and commit changes
exit;
