-- This file (wellknown_ids.sql) contains ASN.1 and IRI names of OIDs which are either
-- a) Root OIDs
-- b) Identifiers which are long arcs
-- c) Well known OIDs
-- d) OIDs where "someone" can register OIDs in these arcs (e.g. a "member body" arc)

-- Root OIDs
insert into `asn1id` (oid, name) values ('oid:0', 'itu-t');
insert into `asn1id` (oid, name) values ('oid:0', 'ccitt');
insert into `asn1id` (oid, name) values ('oid:0', 'itu-r');
insert into `asn1id` (oid, name) values ('oid:1', 'iso');
insert into `asn1id` (oid, name) values ('oid:2', 'joint-iso-itu-t');
insert into `asn1id` (oid, name) values ('oid:2', 'joint-iso-ccitt');
insert into `iri` (oid, name, longarc) values ('oid:0', 'ITU-T', 0);
insert into `iri` (oid, name, longarc) values ('oid:0', 'ITU-R', 0);
insert into `iri` (oid, name, longarc) values ('oid:1', 'ISO', 0);
insert into `iri` (oid, name, longarc) values ('oid:2', 'Joint-ISO-ITU-T', 0);

-- Popular OIDs in the ITU arc (0)
insert into `asn1id` (oid, name) values ('oid:0.2', 'administration');
insert into `asn1id` (oid, name) values ('oid:0.3', 'network-operator');
insert into `asn1id` (oid, name) values ('oid:0.4', 'identified-organization');
insert into `asn1id` (oid, name) values ('oid:0.4.0', 'etsi');
insert into `asn1id` (oid, name) values ('oid:0.4.0.127', 'reserved');
insert into `asn1id` (oid, name) values ('oid:0.4.0.127.0', 'etsi-identified-organization');

-- Popular OIDs in the ISO arc (1)
insert into `asn1id` (oid, name) values ('oid:1.2', 'member-body');
insert into `asn1id` (oid, name) values ('oid:1.2.826.0', 'national');
insert into `asn1id` (oid, name) values ('oid:1.2.826.0.1', 'eng-ltd');
insert into `asn1id` (oid, name) values ('oid:1.2.840.1', 'organization');
insert into `asn1id` (oid, name) values ('oid:1.2.840.1.113883', 'hl7');
insert into `asn1id` (oid, name) values ('oid:1.2.840.113556', 'microsoft');
insert into `asn1id` (oid, name) values ('oid:1.3', 'identified-organization');
insert into `asn1id` (oid, name) values ('oid:1.3.6', 'dod');
insert into `asn1id` (oid, name) values ('oid:1.3.6.1', 'internet');
insert into `asn1id` (oid, name) values ('oid:1.3.6.1.2', 'mgmt');
insert into `asn1id` (oid, name) values ('oid:1.3.6.1.2.1', 'mib-2');
insert into `asn1id` (oid, name) values ('oid:1.3.6.1.4', 'private');
insert into `asn1id` (oid, name) values ('oid:1.3.6.1.4.1', 'enterprise');
insert into `asn1id` (oid, name) values ('oid:1.3.6.1.4.1.37476.9000', 'freeoid');
insert into `iri` (oid, name, longarc) values ('oid:1.2', 'Member-Body', 0);
insert into `iri` (oid, name, longarc) values ('oid:1.3', 'Identified-Organization', 0);
insert into `iri` (oid, name, longarc) values ('oid:1.3.6.1.4.1.37476.9000', 'FreeOID', 0);

-- Popular OIDs in the Joint arc (2)
insert into `asn1id` (oid, name) values ('oid:2.16', 'country');
insert into `asn1id` (oid, name) values ('oid:2.16.840.1', 'organization');
insert into `asn1id` (oid, name) values ('oid:2.23', 'international-organizations');
insert into `asn1id` (oid, name) values ('oid:2.25', 'uuid');
insert into `asn1id` (oid, name) values ('oid:2.40', 'upu');
insert into `asn1id` (oid, name) values ('oid:2.40.2', 'member-body');
insert into `asn1id` (oid, name) values ('oid:2.40.3', 'identified-organization');
insert into `asn1id` (oid, name) values ('oid:2.999', 'example');
insert into `iri` (oid, name, longarc) values ('oid:2.1', 'ASN.1', 1);
insert into `iri` (oid, name, longarc) values ('oid:2.16', 'Country', 1);
insert into `iri` (oid, name, longarc) values ('oid:2.23', 'International-Organizations', 1);
insert into `iri` (oid, name, longarc) values ('oid:2.25', 'UUID', 1);
insert into `iri` (oid, name, longarc) values ('oid:2.27', 'Tag-Based', 1);
insert into `iri` (oid, name, longarc) values ('oid:2.41', 'BIP', 1);
insert into `iri` (oid, name, longarc) values ('oid:2.42', 'Telebiometrics', 1);
insert into `iri` (oid, name, longarc) values ('oid:2.48', 'Cybersecurity', 1);
insert into `iri` (oid, name, longarc) values ('oid:2.49', 'Alerting', 1);
insert into `iri` (oid, name, longarc) values ('oid:2.50', 'OIDResolutionSystem', 1);
insert into `iri` (oid, name, longarc) values ('oid:2.51', 'GS1', 1);
insert into `iri` (oid, name, longarc) values ('oid:2.999', 'Example', 1); -- English
insert into `iri` (oid, name, longarc) values ('oid:2.999', 'Beispiel', 1); -- German
insert into `iri` (oid, name, longarc) values ('oid:2.999', 'Ejemplo', 1); -- Spanish
insert into `iri` (oid, name, longarc) values ('oid:2.999', 'Exemple', 1); -- French
insert into `iri` (oid, name, longarc) values ('oid:2.999', from_base64('0J/RgNC40LzQtdGA'), 1); -- Russian
insert into `iri` (oid, name, longarc) values ('oid:2.999', from_base64('2KfZhNmF2KvYp9mE'), 1); -- Arabic
insert into `iri` (oid, name, longarc) values ('oid:2.999', from_base64('5L6L'), 1); -- Japanese
insert into `iri` (oid, name, longarc) values ('oid:2.999', from_base64('6IyD5L6L'), 1); -- Chinese
insert into `iri` (oid, name, longarc) values ('oid:2.999', from_base64('7JiI7KCc'), 1); -- Korean

-- Country OIDs in the ISO arc (1)
-- Use the tool private/country_getter.phps to generate these lines
insert into `asn1id` (oid, name) values ('oid:1.2.36', 'au'); insert into `iri` (oid, name, longarc) values ('oid:1.2.36', 'AU', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.40', 'at'); insert into `iri` (oid, name, longarc) values ('oid:1.2.40', 'AT', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.56', 'be'); insert into `iri` (oid, name, longarc) values ('oid:1.2.56', 'BE', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.156', 'cn'); insert into `iri` (oid, name, longarc) values ('oid:1.2.156', 'CN', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.203', 'cz'); insert into `iri` (oid, name, longarc) values ('oid:1.2.203', 'CZ', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.208', 'dk'); insert into `iri` (oid, name, longarc) values ('oid:1.2.208', 'DK', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.246', 'fi'); insert into `iri` (oid, name, longarc) values ('oid:1.2.246', 'FI', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.250', 'fr'); insert into `iri` (oid, name, longarc) values ('oid:1.2.250', 'FR', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.276', 'de'); insert into `iri` (oid, name, longarc) values ('oid:1.2.276', 'DE', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.300', 'gr'); insert into `iri` (oid, name, longarc) values ('oid:1.2.300', 'GR', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.344', 'hk'); insert into `iri` (oid, name, longarc) values ('oid:1.2.344', 'HK', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.372', 'ie'); insert into `iri` (oid, name, longarc) values ('oid:1.2.372', 'IE', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.392', 'jp'); insert into `iri` (oid, name, longarc) values ('oid:1.2.392', 'JP', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.398', 'kz'); insert into `iri` (oid, name, longarc) values ('oid:1.2.398', 'KZ', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.410', 'kr'); insert into `iri` (oid, name, longarc) values ('oid:1.2.410', 'KR', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.498', 'md'); insert into `iri` (oid, name, longarc) values ('oid:1.2.498', 'MD', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.528', 'nl'); insert into `iri` (oid, name, longarc) values ('oid:1.2.528', 'NL', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.566', 'ng'); insert into `iri` (oid, name, longarc) values ('oid:1.2.566', 'NG', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.578', 'no'); insert into `iri` (oid, name, longarc) values ('oid:1.2.578', 'NO', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.616', 'pl'); insert into `iri` (oid, name, longarc) values ('oid:1.2.616', 'PL', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.643', 'ru'); insert into `iri` (oid, name, longarc) values ('oid:1.2.643', 'RU', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.702', 'sg'); insert into `iri` (oid, name, longarc) values ('oid:1.2.702', 'SG', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.704', 'vn'); insert into `iri` (oid, name, longarc) values ('oid:1.2.704', 'VN', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.752', 'se'); insert into `iri` (oid, name, longarc) values ('oid:1.2.752', 'SE', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.804', 'ua'); insert into `iri` (oid, name, longarc) values ('oid:1.2.804', 'UA', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.826', 'gb'); insert into `iri` (oid, name, longarc) values ('oid:1.2.826', 'GB', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.840', 'us'); insert into `iri` (oid, name, longarc) values ('oid:1.2.840', 'US', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.860', 'uz'); insert into `iri` (oid, name, longarc) values ('oid:1.2.860', 'UZ', 0);
insert into `asn1id` (oid, name) values ('oid:1.2.862', 've'); insert into `iri` (oid, name, longarc) values ('oid:1.2.862', 'VE', 0);

-- Country OIDs in the Joint arc (1)
-- Use the tool private/country_getter.phps to generate these lines
insert into `asn1id` (oid, name) values ('oid:2.16.4', 'af'); insert into `iri` (oid, name, longarc) values ('oid:2.16.4', 'AF', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.8', 'al'); insert into `iri` (oid, name, longarc) values ('oid:2.16.8', 'AL', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.12', 'dz'); insert into `iri` (oid, name, longarc) values ('oid:2.16.12', 'DZ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.20', 'ad'); insert into `iri` (oid, name, longarc) values ('oid:2.16.20', 'AD', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.24', 'ao'); insert into `iri` (oid, name, longarc) values ('oid:2.16.24', 'AO', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.28', 'ag'); insert into `iri` (oid, name, longarc) values ('oid:2.16.28', 'AG', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.31', 'az'); insert into `iri` (oid, name, longarc) values ('oid:2.16.31', 'AZ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.32', 'ar'); insert into `iri` (oid, name, longarc) values ('oid:2.16.32', 'AR', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.36', 'au'); insert into `iri` (oid, name, longarc) values ('oid:2.16.36', 'AU', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.40', 'at'); insert into `iri` (oid, name, longarc) values ('oid:2.16.40', 'AT', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.44', 'bs'); insert into `iri` (oid, name, longarc) values ('oid:2.16.44', 'BS', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.48', 'bh'); insert into `iri` (oid, name, longarc) values ('oid:2.16.48', 'BH', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.50', 'bd'); insert into `iri` (oid, name, longarc) values ('oid:2.16.50', 'BD', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.51', 'am'); insert into `iri` (oid, name, longarc) values ('oid:2.16.51', 'AM', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.52', 'bb'); insert into `iri` (oid, name, longarc) values ('oid:2.16.52', 'BB', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.56', 'be'); insert into `iri` (oid, name, longarc) values ('oid:2.16.56', 'BE', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.60', 'bm'); insert into `iri` (oid, name, longarc) values ('oid:2.16.60', 'BM', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.64', 'bt'); insert into `iri` (oid, name, longarc) values ('oid:2.16.64', 'BT', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.68', 'bo'); insert into `iri` (oid, name, longarc) values ('oid:2.16.68', 'BO', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.70', 'ba'); insert into `iri` (oid, name, longarc) values ('oid:2.16.70', 'BA', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.72', 'bw'); insert into `iri` (oid, name, longarc) values ('oid:2.16.72', 'BW', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.76', 'br'); insert into `iri` (oid, name, longarc) values ('oid:2.16.76', 'BR', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.84', 'bz'); insert into `iri` (oid, name, longarc) values ('oid:2.16.84', 'BZ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.90', 'sb'); insert into `iri` (oid, name, longarc) values ('oid:2.16.90', 'SB', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.96', 'bn'); insert into `iri` (oid, name, longarc) values ('oid:2.16.96', 'BN', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.100', 'bg'); insert into `iri` (oid, name, longarc) values ('oid:2.16.100', 'BG', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.104', 'mm'); insert into `iri` (oid, name, longarc) values ('oid:2.16.104', 'MM', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.108', 'bi'); insert into `iri` (oid, name, longarc) values ('oid:2.16.108', 'BI', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.112', 'by'); insert into `iri` (oid, name, longarc) values ('oid:2.16.112', 'BY', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.116', 'kh'); insert into `iri` (oid, name, longarc) values ('oid:2.16.116', 'KH', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.120', 'cm'); insert into `iri` (oid, name, longarc) values ('oid:2.16.120', 'CM', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.124', 'ca'); insert into `iri` (oid, name, longarc) values ('oid:2.16.124', 'CA', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.132', 'cv'); insert into `iri` (oid, name, longarc) values ('oid:2.16.132', 'CV', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.140', 'cf'); insert into `iri` (oid, name, longarc) values ('oid:2.16.140', 'CF', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.144', 'lk'); insert into `iri` (oid, name, longarc) values ('oid:2.16.144', 'LK', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.148', 'td'); insert into `iri` (oid, name, longarc) values ('oid:2.16.148', 'TD', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.152', 'cl'); insert into `iri` (oid, name, longarc) values ('oid:2.16.152', 'CL', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.156', 'cn'); insert into `iri` (oid, name, longarc) values ('oid:2.16.156', 'CN', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.158', 'tw'); insert into `iri` (oid, name, longarc) values ('oid:2.16.158', 'TW', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.170', 'co'); insert into `iri` (oid, name, longarc) values ('oid:2.16.170', 'CO', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.174', 'km'); insert into `iri` (oid, name, longarc) values ('oid:2.16.174', 'KM', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.178', 'cg'); insert into `iri` (oid, name, longarc) values ('oid:2.16.178', 'CG', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.180', 'cd'); insert into `iri` (oid, name, longarc) values ('oid:2.16.180', 'CD', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.188', 'cr'); insert into `iri` (oid, name, longarc) values ('oid:2.16.188', 'CR', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.191', 'hr'); insert into `iri` (oid, name, longarc) values ('oid:2.16.191', 'HR', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.192', 'cu'); insert into `iri` (oid, name, longarc) values ('oid:2.16.192', 'CU', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.196', 'cy'); insert into `iri` (oid, name, longarc) values ('oid:2.16.196', 'CY', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.203', 'cz'); insert into `iri` (oid, name, longarc) values ('oid:2.16.203', 'CZ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.204', 'bj'); insert into `iri` (oid, name, longarc) values ('oid:2.16.204', 'BJ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.208', 'dk'); insert into `iri` (oid, name, longarc) values ('oid:2.16.208', 'DK', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.212', 'dm'); insert into `iri` (oid, name, longarc) values ('oid:2.16.212', 'DM', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.214', 'do'); insert into `iri` (oid, name, longarc) values ('oid:2.16.214', 'DO', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.218', 'ec'); insert into `iri` (oid, name, longarc) values ('oid:2.16.218', 'EC', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.222', 'sv'); insert into `iri` (oid, name, longarc) values ('oid:2.16.222', 'SV', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.226', 'gq'); insert into `iri` (oid, name, longarc) values ('oid:2.16.226', 'GQ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.231', 'et'); insert into `iri` (oid, name, longarc) values ('oid:2.16.231', 'ET', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.232', 'er'); insert into `iri` (oid, name, longarc) values ('oid:2.16.232', 'ER', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.233', 'ee'); insert into `iri` (oid, name, longarc) values ('oid:2.16.233', 'EE', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.242', 'fj'); insert into `iri` (oid, name, longarc) values ('oid:2.16.242', 'FJ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.246', 'fi'); insert into `iri` (oid, name, longarc) values ('oid:2.16.246', 'FI', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.250', 'fr'); insert into `iri` (oid, name, longarc) values ('oid:2.16.250', 'FR', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.262', 'dj'); insert into `iri` (oid, name, longarc) values ('oid:2.16.262', 'DJ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.266', 'ga'); insert into `iri` (oid, name, longarc) values ('oid:2.16.266', 'GA', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.268', 'ge'); insert into `iri` (oid, name, longarc) values ('oid:2.16.268', 'GE', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.270', 'gm'); insert into `iri` (oid, name, longarc) values ('oid:2.16.270', 'GM', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.275', 'ps'); insert into `iri` (oid, name, longarc) values ('oid:2.16.275', 'PS', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.276', 'de'); insert into `iri` (oid, name, longarc) values ('oid:2.16.276', 'DE', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.288', 'gh'); insert into `iri` (oid, name, longarc) values ('oid:2.16.288', 'GH', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.296', 'ki'); insert into `iri` (oid, name, longarc) values ('oid:2.16.296', 'KI', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.300', 'gr'); insert into `iri` (oid, name, longarc) values ('oid:2.16.300', 'GR', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.308', 'gd'); insert into `iri` (oid, name, longarc) values ('oid:2.16.308', 'GD', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.320', 'gt'); insert into `iri` (oid, name, longarc) values ('oid:2.16.320', 'GT', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.324', 'gn'); insert into `iri` (oid, name, longarc) values ('oid:2.16.324', 'GN', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.328', 'gy'); insert into `iri` (oid, name, longarc) values ('oid:2.16.328', 'GY', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.332', 'ht'); insert into `iri` (oid, name, longarc) values ('oid:2.16.332', 'HT', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.336', 'va'); insert into `iri` (oid, name, longarc) values ('oid:2.16.336', 'VA', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.340', 'hn'); insert into `iri` (oid, name, longarc) values ('oid:2.16.340', 'HN', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.344', 'hk'); insert into `iri` (oid, name, longarc) values ('oid:2.16.344', 'HK', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.348', 'hu'); insert into `iri` (oid, name, longarc) values ('oid:2.16.348', 'HU', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.352', 'is'); insert into `iri` (oid, name, longarc) values ('oid:2.16.352', 'IS', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.356', 'in'); insert into `iri` (oid, name, longarc) values ('oid:2.16.356', 'IN', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.360', 'id'); insert into `iri` (oid, name, longarc) values ('oid:2.16.360', 'ID', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.364', 'ir'); insert into `iri` (oid, name, longarc) values ('oid:2.16.364', 'IR', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.368', 'iq'); insert into `iri` (oid, name, longarc) values ('oid:2.16.368', 'IQ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.372', 'ie'); insert into `iri` (oid, name, longarc) values ('oid:2.16.372', 'IE', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.376', 'il'); insert into `iri` (oid, name, longarc) values ('oid:2.16.376', 'IL', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.380', 'it'); insert into `iri` (oid, name, longarc) values ('oid:2.16.380', 'IT', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.384', 'ci'); insert into `iri` (oid, name, longarc) values ('oid:2.16.384', 'CI', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.388', 'jm'); insert into `iri` (oid, name, longarc) values ('oid:2.16.388', 'JM', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.392', 'jp'); insert into `iri` (oid, name, longarc) values ('oid:2.16.392', 'JP', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.398', 'kz'); insert into `iri` (oid, name, longarc) values ('oid:2.16.398', 'KZ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.400', 'jo'); insert into `iri` (oid, name, longarc) values ('oid:2.16.400', 'JO', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.404', 'ke'); insert into `iri` (oid, name, longarc) values ('oid:2.16.404', 'KE', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.408', 'kp'); insert into `iri` (oid, name, longarc) values ('oid:2.16.408', 'KP', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.410', 'kr'); insert into `iri` (oid, name, longarc) values ('oid:2.16.410', 'KR', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.414', 'kw'); insert into `iri` (oid, name, longarc) values ('oid:2.16.414', 'KW', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.417', 'kg'); insert into `iri` (oid, name, longarc) values ('oid:2.16.417', 'KG', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.418', 'la'); insert into `iri` (oid, name, longarc) values ('oid:2.16.418', 'LA', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.422', 'lb'); insert into `iri` (oid, name, longarc) values ('oid:2.16.422', 'LB', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.426', 'ls'); insert into `iri` (oid, name, longarc) values ('oid:2.16.426', 'LS', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.428', 'lv'); insert into `iri` (oid, name, longarc) values ('oid:2.16.428', 'LV', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.430', 'lr'); insert into `iri` (oid, name, longarc) values ('oid:2.16.430', 'LR', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.434', 'ly'); insert into `iri` (oid, name, longarc) values ('oid:2.16.434', 'LY', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.438', 'li'); insert into `iri` (oid, name, longarc) values ('oid:2.16.438', 'LI', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.440', 'lt'); insert into `iri` (oid, name, longarc) values ('oid:2.16.440', 'LT', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.442', 'lu'); insert into `iri` (oid, name, longarc) values ('oid:2.16.442', 'LU', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.450', 'mg'); insert into `iri` (oid, name, longarc) values ('oid:2.16.450', 'MG', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.454', 'mw'); insert into `iri` (oid, name, longarc) values ('oid:2.16.454', 'MW', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.458', 'my'); insert into `iri` (oid, name, longarc) values ('oid:2.16.458', 'MY', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.462', 'mv'); insert into `iri` (oid, name, longarc) values ('oid:2.16.462', 'MV', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.466', 'ml'); insert into `iri` (oid, name, longarc) values ('oid:2.16.466', 'ML', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.470', 'mt'); insert into `iri` (oid, name, longarc) values ('oid:2.16.470', 'MT', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.478', 'mr'); insert into `iri` (oid, name, longarc) values ('oid:2.16.478', 'MR', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.480', 'mu'); insert into `iri` (oid, name, longarc) values ('oid:2.16.480', 'MU', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.484', 'mx'); insert into `iri` (oid, name, longarc) values ('oid:2.16.484', 'MX', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.492', 'mc'); insert into `iri` (oid, name, longarc) values ('oid:2.16.492', 'MC', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.496', 'mn'); insert into `iri` (oid, name, longarc) values ('oid:2.16.496', 'MN', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.498', 'md'); insert into `iri` (oid, name, longarc) values ('oid:2.16.498', 'MD', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.499', 'me'); insert into `iri` (oid, name, longarc) values ('oid:2.16.499', 'ME', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.504', 'ma'); insert into `iri` (oid, name, longarc) values ('oid:2.16.504', 'MA', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.508', 'mz'); insert into `iri` (oid, name, longarc) values ('oid:2.16.508', 'MZ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.512', 'om'); insert into `iri` (oid, name, longarc) values ('oid:2.16.512', 'OM', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.516', 'na'); insert into `iri` (oid, name, longarc) values ('oid:2.16.516', 'NA', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.520', 'nr'); insert into `iri` (oid, name, longarc) values ('oid:2.16.520', 'NR', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.524', 'np'); insert into `iri` (oid, name, longarc) values ('oid:2.16.524', 'NP', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.528', 'nl'); insert into `iri` (oid, name, longarc) values ('oid:2.16.528', 'NL', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.530', 'an'); insert into `iri` (oid, name, longarc) values ('oid:2.16.530', 'AN', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.548', 'vu'); insert into `iri` (oid, name, longarc) values ('oid:2.16.548', 'VU', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.554', 'nz'); insert into `iri` (oid, name, longarc) values ('oid:2.16.554', 'NZ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.558', 'ni'); insert into `iri` (oid, name, longarc) values ('oid:2.16.558', 'NI', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.562', 'ne'); insert into `iri` (oid, name, longarc) values ('oid:2.16.562', 'NE', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.566', 'ng'); insert into `iri` (oid, name, longarc) values ('oid:2.16.566', 'NG', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.578', 'no'); insert into `iri` (oid, name, longarc) values ('oid:2.16.578', 'NO', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.583', 'fm'); insert into `iri` (oid, name, longarc) values ('oid:2.16.583', 'FM', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.584', 'mh'); insert into `iri` (oid, name, longarc) values ('oid:2.16.584', 'MH', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.585', 'pw'); insert into `iri` (oid, name, longarc) values ('oid:2.16.585', 'PW', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.586', 'pk'); insert into `iri` (oid, name, longarc) values ('oid:2.16.586', 'PK', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.591', 'pa'); insert into `iri` (oid, name, longarc) values ('oid:2.16.591', 'PA', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.598', 'pg'); insert into `iri` (oid, name, longarc) values ('oid:2.16.598', 'PG', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.600', 'py'); insert into `iri` (oid, name, longarc) values ('oid:2.16.600', 'PY', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.604', 'pe'); insert into `iri` (oid, name, longarc) values ('oid:2.16.604', 'PE', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.608', 'ph'); insert into `iri` (oid, name, longarc) values ('oid:2.16.608', 'PH', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.616', 'pl'); insert into `iri` (oid, name, longarc) values ('oid:2.16.616', 'PL', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.620', 'pt'); insert into `iri` (oid, name, longarc) values ('oid:2.16.620', 'PT', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.624', 'gw'); insert into `iri` (oid, name, longarc) values ('oid:2.16.624', 'GW', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.626', 'tl'); insert into `iri` (oid, name, longarc) values ('oid:2.16.626', 'TL', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.634', 'qa'); insert into `iri` (oid, name, longarc) values ('oid:2.16.634', 'QA', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.642', 'ro'); insert into `iri` (oid, name, longarc) values ('oid:2.16.642', 'RO', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.643', 'ru'); insert into `iri` (oid, name, longarc) values ('oid:2.16.643', 'RU', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.646', 'rw'); insert into `iri` (oid, name, longarc) values ('oid:2.16.646', 'RW', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.659', 'kn'); insert into `iri` (oid, name, longarc) values ('oid:2.16.659', 'KN', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.662', 'lc'); insert into `iri` (oid, name, longarc) values ('oid:2.16.662', 'LC', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.670', 'vc'); insert into `iri` (oid, name, longarc) values ('oid:2.16.670', 'VC', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.674', 'sm'); insert into `iri` (oid, name, longarc) values ('oid:2.16.674', 'SM', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.678', 'st'); insert into `iri` (oid, name, longarc) values ('oid:2.16.678', 'ST', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.682', 'sa'); insert into `iri` (oid, name, longarc) values ('oid:2.16.682', 'SA', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.686', 'sn'); insert into `iri` (oid, name, longarc) values ('oid:2.16.686', 'SN', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.688', 'rs'); insert into `iri` (oid, name, longarc) values ('oid:2.16.688', 'RS', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.690', 'sc'); insert into `iri` (oid, name, longarc) values ('oid:2.16.690', 'SC', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.694', 'sl'); insert into `iri` (oid, name, longarc) values ('oid:2.16.694', 'SL', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.702', 'sg'); insert into `iri` (oid, name, longarc) values ('oid:2.16.702', 'SG', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.703', 'sk'); insert into `iri` (oid, name, longarc) values ('oid:2.16.703', 'SK', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.704', 'vn'); insert into `iri` (oid, name, longarc) values ('oid:2.16.704', 'VN', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.705', 'si'); insert into `iri` (oid, name, longarc) values ('oid:2.16.705', 'SI', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.706', 'so'); insert into `iri` (oid, name, longarc) values ('oid:2.16.706', 'SO', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.710', 'za'); insert into `iri` (oid, name, longarc) values ('oid:2.16.710', 'ZA', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.716', 'zw'); insert into `iri` (oid, name, longarc) values ('oid:2.16.716', 'ZW', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.724', 'es'); insert into `iri` (oid, name, longarc) values ('oid:2.16.724', 'ES', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.728', 'ss'); insert into `iri` (oid, name, longarc) values ('oid:2.16.728', 'SS', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.729', 'sd'); insert into `iri` (oid, name, longarc) values ('oid:2.16.729', 'SD', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.740', 'sr'); insert into `iri` (oid, name, longarc) values ('oid:2.16.740', 'SR', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.748', 'sz'); insert into `iri` (oid, name, longarc) values ('oid:2.16.748', 'SZ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.752', 'se'); insert into `iri` (oid, name, longarc) values ('oid:2.16.752', 'SE', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.756', 'ch'); insert into `iri` (oid, name, longarc) values ('oid:2.16.756', 'CH', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.760', 'sy'); insert into `iri` (oid, name, longarc) values ('oid:2.16.760', 'SY', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.762', 'tj'); insert into `iri` (oid, name, longarc) values ('oid:2.16.762', 'TJ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.764', 'th'); insert into `iri` (oid, name, longarc) values ('oid:2.16.764', 'TH', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.768', 'tg'); insert into `iri` (oid, name, longarc) values ('oid:2.16.768', 'TG', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.776', 'to'); insert into `iri` (oid, name, longarc) values ('oid:2.16.776', 'TO', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.780', 'tt'); insert into `iri` (oid, name, longarc) values ('oid:2.16.780', 'TT', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.784', 'ae'); insert into `iri` (oid, name, longarc) values ('oid:2.16.784', 'AE', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.788', 'tn'); insert into `iri` (oid, name, longarc) values ('oid:2.16.788', 'TN', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.792', 'tr'); insert into `iri` (oid, name, longarc) values ('oid:2.16.792', 'TR', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.795', 'tm'); insert into `iri` (oid, name, longarc) values ('oid:2.16.795', 'TM', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.798', 'tv'); insert into `iri` (oid, name, longarc) values ('oid:2.16.798', 'TV', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.800', 'ug'); insert into `iri` (oid, name, longarc) values ('oid:2.16.800', 'UG', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.804', 'ua'); insert into `iri` (oid, name, longarc) values ('oid:2.16.804', 'UA', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.807', 'mk'); insert into `iri` (oid, name, longarc) values ('oid:2.16.807', 'MK', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.818', 'eg'); insert into `iri` (oid, name, longarc) values ('oid:2.16.818', 'EG', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.826', 'gb'); insert into `iri` (oid, name, longarc) values ('oid:2.16.826', 'GB', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.834', 'tz'); insert into `iri` (oid, name, longarc) values ('oid:2.16.834', 'TZ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.840', 'us'); insert into `iri` (oid, name, longarc) values ('oid:2.16.840', 'US', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.854', 'bf'); insert into `iri` (oid, name, longarc) values ('oid:2.16.854', 'BF', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.858', 'uy'); insert into `iri` (oid, name, longarc) values ('oid:2.16.858', 'UY', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.860', 'uz'); insert into `iri` (oid, name, longarc) values ('oid:2.16.860', 'UZ', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.862', 've'); insert into `iri` (oid, name, longarc) values ('oid:2.16.862', 'VE', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.882', 'ws'); insert into `iri` (oid, name, longarc) values ('oid:2.16.882', 'WS', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.887', 'ye'); insert into `iri` (oid, name, longarc) values ('oid:2.16.887', 'YE', 0);
insert into `asn1id` (oid, name) values ('oid:2.16.894', 'zm'); insert into `iri` (oid, name, longarc) values ('oid:2.16.894', 'ZM', 0);
