-- This file (wellknown_ids.sql) contains ASN.1 and IRI names of OIDs which are either
-- a) Root OIDs
-- b) Identifiers which are long arcs
-- c) Well known OIDs
-- d) OIDs where "someone" can register OIDs in these arcs (e.g. a "member body" arc)

-- Root OIDs
insert into `asn1id` (oid, name, well_known) values ('oid:0', 'itu-t', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:0', 'ccitt', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:0', 'itu-r', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1', 'iso', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:2', 'joint-iso-itu-t', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:2', 'joint-iso-ccitt', 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:0', 'ITU-T', 0, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:0', 'ITU-R', 0, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:1', 'ISO', 0, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:2', 'Joint-ISO-ITU-T', 0, 1);

-- Popular OIDs in the ITU arc (0)
insert into `asn1id` (oid, name, well_known) values ('oid:0.2', 'administration', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:0.3', 'network-operator', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:0.4', 'identified-organization', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:0.4.0', 'etsi', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:0.4.0.127', 'reserved', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:0.4.0.127.0', 'etsi-identified-organization', 1);

-- Popular OIDs in the ISO arc (1)
insert into `asn1id` (oid, name, well_known) values ('oid:1.2', 'member-body', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1.2.826.0', 'national', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1.2.826.0.1', 'eng-ltd', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1.2.840.1', 'organization', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1.2.840.1.113883', 'hl7', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1.2.840.113556', 'microsoft', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1.3', 'identified-organization', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1.3.6', 'dod', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1.3.6.1', 'internet', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1.3.6.1.2', 'mgmt', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1.3.6.1.2.1', 'mib-2', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1.3.6.1.4', 'private', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1.3.6.1.4.1', 'enterprise', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:1.3.6.1.4.1.37476.9000', 'freeoid', 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:1.2', 'Member-Body', 0, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:1.3', 'Identified-Organization', 0, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:1.3.6.1.4.1.37476.9000', 'FreeOID', 0, 1);

-- Popular OIDs in the Joint arc (2)
insert into `asn1id` (oid, name, well_known) values ('oid:2.16', 'country', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:2.16.840.1', 'organization', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:2.23', 'international-organizations', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:2.25', 'uuid', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:2.40', 'upu', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:2.40.2', 'member-body', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:2.40.3', 'identified-organization', 1);
insert into `asn1id` (oid, name, well_known) values ('oid:2.999', 'example', 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.1', 'ASN.1', 1, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.16', 'Country', 1, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.23', 'International-Organizations', 1, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.25', 'UUID', 1, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.27', 'Tag-Based', 1, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.41', 'BIP', 1, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.42', 'Telebiometrics', 1, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.48', 'Cybersecurity', 1, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.49', 'Alerting', 1, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.50', 'OIDResolutionSystem', 1, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.51', 'GS1', 1, 1);
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.999', 'Example', 1, 1); -- English
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.999', 'Beispiel', 1, 1); -- German
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.999', 'Ejemplo', 1, 1); -- Spanish
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.999', 'Exemple', 1, 1); -- French
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.999', from_base64('0J/RgNC40LzQtdGA'), 1, 1); -- Russian
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.999', from_base64('2KfZhNmF2KvYp9mE'), 1, 1); -- Arabic
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.999', from_base64('5L6L'), 1, 1); -- Japanese
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.999', from_base64('6IyD5L6L'), 1, 1); -- Chinese
insert into `iri` (oid, name, longarc, well_known) values ('oid:2.999', from_base64('7JiI7KCc'), 1, 1); -- Korean

-- Country OIDs
-- Use the tool private/country_getter.phps to generate these lines
insert into asn1id (oid, name, well_known) values ('oid:1.2.36', 'au', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.36', 'AU', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.40', 'at', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.40', 'AT', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.56', 'be', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.56', 'BE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.156', 'cn', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.156', 'CN', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.203', 'cz', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.203', 'CZ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.208', 'dk', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.208', 'DK', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.246', 'fi', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.246', 'FI', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.250', 'fr', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.250', 'FR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.276', 'de', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.276', 'DE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.300', 'gr', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.300', 'GR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.344', 'hk', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.344', 'HK', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.372', 'ie', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.372', 'IE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.392', 'jp', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.392', 'JP', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.398', 'kz', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.398', 'KZ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.410', 'kr', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.410', 'KR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.498', 'md', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.498', 'MD', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.528', 'nl', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.528', 'NL', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.566', 'ng', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.566', 'NG', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.578', 'no', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.578', 'NO', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.616', 'pl', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.616', 'PL', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.643', 'ru', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.643', 'RU', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.702', 'sg', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.702', 'SG', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.704', 'vn', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.704', 'VN', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.752', 'se', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.752', 'SE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.804', 'ua', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.804', 'UA', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.826', 'gb', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.826', 'GB', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.840', 'us', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.840', 'US', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.860', 'uz', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.860', 'UZ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:1.2.862', 've', 1); insert into iri (oid, name, longarc, well_known) values ('oid:1.2.862', 'VE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.4', 'af', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.4', 'AF', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.8', 'al', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.8', 'AL', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.12', 'dz', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.12', 'DZ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.20', 'ad', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.20', 'AD', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.24', 'ao', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.24', 'AO', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.28', 'ag', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.28', 'AG', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.31', 'az', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.31', 'AZ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.32', 'ar', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.32', 'AR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.36', 'au', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.36', 'AU', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.40', 'at', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.40', 'AT', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.44', 'bs', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.44', 'BS', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.48', 'bh', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.48', 'BH', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.50', 'bd', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.50', 'BD', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.51', 'am', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.51', 'AM', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.52', 'bb', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.52', 'BB', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.56', 'be', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.56', 'BE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.60', 'bm', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.60', 'BM', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.64', 'bt', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.64', 'BT', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.68', 'bo', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.68', 'BO', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.70', 'ba', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.70', 'BA', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.72', 'bw', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.72', 'BW', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.76', 'br', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.76', 'BR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.84', 'bz', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.84', 'BZ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.90', 'sb', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.90', 'SB', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.96', 'bn', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.96', 'BN', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.100', 'bg', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.100', 'BG', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.104', 'mm', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.104', 'MM', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.108', 'bi', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.108', 'BI', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.112', 'by', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.112', 'BY', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.116', 'kh', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.116', 'KH', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.120', 'cm', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.120', 'CM', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.124', 'ca', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.124', 'CA', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.132', 'cv', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.132', 'CV', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.140', 'cf', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.140', 'CF', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.144', 'lk', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.144', 'LK', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.148', 'td', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.148', 'TD', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.152', 'cl', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.152', 'CL', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.156', 'cn', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.156', 'CN', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.158', 'tw', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.158', 'TW', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.170', 'co', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.170', 'CO', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.174', 'km', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.174', 'KM', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.178', 'cg', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.178', 'CG', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.180', 'cd', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.180', 'CD', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.188', 'cr', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.188', 'CR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.191', 'hr', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.191', 'HR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.192', 'cu', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.192', 'CU', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.196', 'cy', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.196', 'CY', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.203', 'cz', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.203', 'CZ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.204', 'bj', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.204', 'BJ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.208', 'dk', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.208', 'DK', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.212', 'dm', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.212', 'DM', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.214', 'do', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.214', 'DO', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.218', 'ec', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.218', 'EC', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.222', 'sv', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.222', 'SV', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.226', 'gq', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.226', 'GQ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.231', 'et', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.231', 'ET', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.232', 'er', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.232', 'ER', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.233', 'ee', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.233', 'EE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.242', 'fj', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.242', 'FJ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.246', 'fi', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.246', 'FI', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.250', 'fr', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.250', 'FR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.262', 'dj', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.262', 'DJ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.266', 'ga', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.266', 'GA', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.268', 'ge', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.268', 'GE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.270', 'gm', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.270', 'GM', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.275', 'ps', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.275', 'PS', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.276', 'de', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.276', 'DE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.288', 'gh', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.288', 'GH', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.296', 'ki', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.296', 'KI', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.300', 'gr', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.300', 'GR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.308', 'gd', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.308', 'GD', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.320', 'gt', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.320', 'GT', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.324', 'gn', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.324', 'GN', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.328', 'gy', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.328', 'GY', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.332', 'ht', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.332', 'HT', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.336', 'va', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.336', 'VA', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.340', 'hn', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.340', 'HN', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.344', 'hk', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.344', 'HK', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.348', 'hu', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.348', 'HU', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.352', 'is', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.352', 'IS', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.356', 'in', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.356', 'IN', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.360', 'id', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.360', 'ID', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.364', 'ir', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.364', 'IR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.368', 'iq', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.368', 'IQ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.372', 'ie', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.372', 'IE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.376', 'il', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.376', 'IL', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.380', 'it', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.380', 'IT', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.384', 'ci', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.384', 'CI', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.388', 'jm', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.388', 'JM', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.392', 'jp', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.392', 'JP', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.398', 'kz', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.398', 'KZ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.400', 'jo', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.400', 'JO', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.404', 'ke', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.404', 'KE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.408', 'kp', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.408', 'KP', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.410', 'kr', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.410', 'KR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.414', 'kw', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.414', 'KW', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.417', 'kg', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.417', 'KG', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.418', 'la', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.418', 'LA', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.422', 'lb', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.422', 'LB', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.426', 'ls', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.426', 'LS', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.428', 'lv', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.428', 'LV', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.430', 'lr', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.430', 'LR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.434', 'ly', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.434', 'LY', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.438', 'li', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.438', 'LI', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.440', 'lt', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.440', 'LT', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.442', 'lu', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.442', 'LU', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.450', 'mg', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.450', 'MG', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.454', 'mw', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.454', 'MW', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.458', 'my', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.458', 'MY', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.462', 'mv', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.462', 'MV', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.466', 'ml', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.466', 'ML', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.470', 'mt', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.470', 'MT', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.478', 'mr', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.478', 'MR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.480', 'mu', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.480', 'MU', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.484', 'mx', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.484', 'MX', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.492', 'mc', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.492', 'MC', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.496', 'mn', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.496', 'MN', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.498', 'md', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.498', 'MD', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.499', 'me', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.499', 'ME', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.504', 'ma', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.504', 'MA', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.508', 'mz', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.508', 'MZ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.512', 'om', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.512', 'OM', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.516', 'na', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.516', 'NA', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.520', 'nr', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.520', 'NR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.524', 'np', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.524', 'NP', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.528', 'nl', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.528', 'NL', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.530', 'an', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.530', 'AN', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.548', 'vu', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.548', 'VU', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.554', 'nz', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.554', 'NZ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.558', 'ni', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.558', 'NI', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.562', 'ne', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.562', 'NE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.566', 'ng', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.566', 'NG', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.578', 'no', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.578', 'NO', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.583', 'fm', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.583', 'FM', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.584', 'mh', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.584', 'MH', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.585', 'pw', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.585', 'PW', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.586', 'pk', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.586', 'PK', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.591', 'pa', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.591', 'PA', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.598', 'pg', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.598', 'PG', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.600', 'py', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.600', 'PY', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.604', 'pe', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.604', 'PE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.608', 'ph', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.608', 'PH', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.616', 'pl', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.616', 'PL', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.620', 'pt', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.620', 'PT', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.624', 'gw', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.624', 'GW', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.626', 'tl', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.626', 'TL', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.634', 'qa', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.634', 'QA', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.642', 'ro', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.642', 'RO', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.643', 'ru', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.643', 'RU', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.646', 'rw', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.646', 'RW', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.659', 'kn', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.659', 'KN', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.662', 'lc', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.662', 'LC', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.670', 'vc', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.670', 'VC', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.674', 'sm', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.674', 'SM', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.678', 'st', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.678', 'ST', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.682', 'sa', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.682', 'SA', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.686', 'sn', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.686', 'SN', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.688', 'rs', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.688', 'RS', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.690', 'sc', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.690', 'SC', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.694', 'sl', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.694', 'SL', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.702', 'sg', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.702', 'SG', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.703', 'sk', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.703', 'SK', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.704', 'vn', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.704', 'VN', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.705', 'si', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.705', 'SI', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.706', 'so', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.706', 'SO', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.710', 'za', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.710', 'ZA', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.716', 'zw', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.716', 'ZW', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.724', 'es', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.724', 'ES', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.728', 'ss', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.728', 'SS', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.729', 'sd', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.729', 'SD', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.740', 'sr', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.740', 'SR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.748', 'sz', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.748', 'SZ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.752', 'se', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.752', 'SE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.756', 'ch', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.756', 'CH', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.760', 'sy', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.760', 'SY', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.762', 'tj', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.762', 'TJ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.764', 'th', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.764', 'TH', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.768', 'tg', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.768', 'TG', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.776', 'to', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.776', 'TO', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.780', 'tt', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.780', 'TT', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.784', 'ae', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.784', 'AE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.788', 'tn', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.788', 'TN', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.792', 'tr', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.792', 'TR', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.795', 'tm', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.795', 'TM', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.798', 'tv', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.798', 'TV', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.800', 'ug', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.800', 'UG', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.804', 'ua', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.804', 'UA', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.807', 'mk', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.807', 'MK', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.818', 'eg', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.818', 'EG', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.826', 'gb', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.826', 'GB', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.834', 'tz', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.834', 'TZ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.840', 'us', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.840', 'US', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.854', 'bf', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.854', 'BF', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.858', 'uy', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.858', 'UY', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.860', 'uz', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.860', 'UZ', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.862', 've', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.862', 'VE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.882', 'ws', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.882', 'WS', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.887', 'ye', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.887', 'YE', 0, 1);
insert into asn1id (oid, name, well_known) values ('oid:2.16.894', 'zm', 1); insert into iri (oid, name, longarc, well_known) values ('oid:2.16.894', 'ZM', 0, 1);
-- Country getter checksum 688f2ff3
